### ISSUE TITLE
Descobrir com vai funcionar o sistema de encriptação

### ISSUE THREAD

**Issue by BomDia12** [BomDia12/Rust-Password-Manager#1]
- [x] Escolher qual será a forma de encriptação utilizada no projeto
   - [x] A chave de encriptação tem que ser obtida a partir da senha do usuário 
   - [x] Deve ser possível desencriptar as senhas
 - [x] Procurar por bibliotecas de rust que implementem essa encriptação.

**Comment by Leir-Cruz** [comment]
### Modelo Escolhido
- Aes (Rindjael Encryption)

### Chave de encriptação
- expansão da chave utilizando repetição até o número de bits desejado (128, 192 ou 256)
- expansão da chave usando hash

### Cifra e Decifração
- são feitas em blocos de 128, 192 ou 256 bits

**Comment by Leir-Cruz** [comment]
### Cifração e Decifação
- Aes (Advanced Encryption Standard)

### Chave de encriptação
- Expansão de chave utilizando repetição até o número de bits desejados

### Biblioteca rust 
- https://crates.io/crates/aes
